#Applicatio ruinning port
server:
  port: 8809

#Database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoaibReimbursement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    jdbc:
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  security:
    filter:
      order: 10


jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization



logging:
  level:
    org:
      springframework:
        security=TRACE: TRACE